services:
  onvif2mqtt:
    build: .
    container_name: ONVIF2MQTT
    # A configuration file is required.
    # See config.example.yml for an example.
    volumes:
      - type: bind
        source: ./config.yml
        target: /app/config.yml
    restart: always
    # Optional debugging.
    # environment:
    #  DEBUG: onvif2mqtt
